// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface Product {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	description?: string;
	images?: {
		id: string;
		src?: string;
		alt?: string;
		width?: number;
		height?: number;
		provider?: string;
		previewUrl?: string;
		meta?: Record<string, unknown>;
	};
	commerce?: unknown;
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	bylines?: ContentBylineCredit[];
	terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
	interface EmDashCollections {
		products: Product;
	}
}
