/**
 * Site-local ambient declarations.
 *
 * `virtual:emdash/env` is generated by EmDash's Astro integration at build
 * time and is typed in the emdash package's own `src/virtual-modules.d.ts` —
 * which that package does not ship through its `exports` map, so nothing here
 * can reference it. The declaration is reproduced (not widened) below so
 * `astro check` can see the one module `src/lib/webhook-env.ts` imports.
 */
declare module "virtual:emdash/env" {
	/**
	 * Worker bindings and secrets. Cloudflare's `env` (from `cloudflare:workers`)
	 * under `@astrojs/cloudflare`; `undefined` under any other adapter, which is
	 * why every read of it must tolerate the object being absent.
	 */
	export const env: Record<string, unknown> | undefined;
}
